"""
Novus ATS - Weighted Scoring Engine

Converts ATS matching and resume structure analysis into an explainable
0-100 ATS score.

Novus ATS v1 weights:

    Required Skills          30%
    Technical Keywords       15%
    Practical Experience     20%
    Responsibilities         15%
    Formatting / Parseability 10%
    Education                 5%
    Preferred Skills          5%

Total = 100%

This module does not:
- parse resumes
- parse job descriptions
- perform keyword matching
- use AI
- rewrite resume content
"""

from __future__ import annotations

from typing import Any


# ---------------------------------------------------------------------------
# Novus ATS v1 scoring weights
# ---------------------------------------------------------------------------

DEFAULT_WEIGHTS = {
    "required_skills": 30.0,
    "technical_keywords": 15.0,
    "practical_experience": 20.0,
    "responsibilities": 15.0,
    "parseability": 10.0,
    "education": 5.0,
    "preferred_skills": 5.0,
}


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _safe_list(value: Any) -> list:
    """Return a list when the supplied value is actually a list."""
    return value if isinstance(value, list) else []


def _category_match_rate(category: Any) -> float | None:
    """
    Calculate a category match percentage.

    Returns:
        0-100 when requirements exist.
        None when there is nothing to evaluate.
    """
    if not isinstance(category, dict):
        return None

    matched = _safe_list(category.get("matched"))
    missing = _safe_list(category.get("missing"))

    total = len(matched) + len(missing)

    if total == 0:
        return None

    return (len(matched) / total) * 100.0


def _round_score(value: float) -> float:
    """Keep scores deterministic and readable."""
    return round(value, 2)


# ---------------------------------------------------------------------------
# Practical experience
# ---------------------------------------------------------------------------

def _calculate_practical_experience(
    match_analysis: dict[str, Any],
    resume_analysis: dict[str, Any] | None,
) -> float | None:
    """
    Calculate the practical-experience score.

    Practical experience is intentionally broader than employment history,
    especially for students and early-career candidates.

    It considers:
        - internships / employment experience
        - relevant projects
        - certifications

    When ATS-03 has no experience requirements, we use the resume's
    available practical evidence as a structural signal.

    The detailed relevance analysis can be improved later in ATS-05.
    """
    experience = match_analysis.get("experience")

    experience_score = _category_match_rate(experience)

    if experience_score is not None:
        return experience_score

    if not isinstance(resume_analysis, dict):
        return None

    experience_items = _safe_list(
        resume_analysis.get("experience")
    )

    project_items = _safe_list(
        resume_analysis.get("projects")
    )

    certification_items = _safe_list(
        resume_analysis.get("certifications")
    )

    total_items = (
        len(experience_items)
        + len(project_items)
        + len(certification_items)
    )

    if total_items == 0:
        return None

    # At this stage, the existence of practical evidence is enough to
    # make the category evaluable. ATS-05 will provide more detailed
    # relevance/gap analysis.
    #
    # We use a capped baseline rather than awarding 100 merely because
    # something exists.
    #
    # This keeps ATS-04 conservative until relevance analysis is available.
    if experience_items and project_items:
        return 100.0

    if experience_items or project_items:
        return 80.0

    if certification_items:
        return 60.0

    return None


# ---------------------------------------------------------------------------
# Parseability
# ---------------------------------------------------------------------------

def _calculate_parseability(
    parseability_analysis: dict[str, Any] | None,
) -> float | None:
    """
    Extract the parseability score from a parseability analysis.

    Expected structure:

        {
            "score": 0-100
        }

    Parseability will be generated by the resume structure/parseability
    analyzer and is deliberately kept separate from keyword matching.
    """
    if not isinstance(parseability_analysis, dict):
        return None

    score = parseability_analysis.get("score")

    if not isinstance(score, (int, float)):
        return None

    return max(0.0, min(100.0, float(score)))


# ---------------------------------------------------------------------------
# Component scores
# ---------------------------------------------------------------------------

def calculate_component_scores(
    match_analysis: dict[str, Any],
    *,
    resume_analysis: dict[str, Any] | None = None,
    parseability_analysis: dict[str, Any] | None = None,
) -> dict[str, float | None]:
    """
    Calculate individual ATS component scores.
    """
    if not isinstance(match_analysis, dict):
        raise ValueError("Match analysis must be a dictionary.")

    return {
        "required_skills": _category_match_rate(
            match_analysis.get("required_skills")
        ),

        "technical_keywords": _category_match_rate(
            match_analysis.get("technical_keywords")
        ),

        "practical_experience": _calculate_practical_experience(
            match_analysis,
            resume_analysis,
        ),

        "responsibilities": _category_match_rate(
            match_analysis.get("responsibilities")
        ),

        "parseability": _calculate_parseability(
            parseability_analysis
        ),

        "education": _category_match_rate(
            match_analysis.get("education")
        ),

        "preferred_skills": _category_match_rate(
            match_analysis.get("preferred_skills")
        ),
    }


# ---------------------------------------------------------------------------
# Weight redistribution
# ---------------------------------------------------------------------------

def _active_weights(
    component_scores: dict[str, float | None],
    weights: dict[str, float],
) -> dict[str, float]:
    """
    Redistribute weights belonging to unavailable categories.

    If a JD contains no education requirement, for example, education does
    not become a zero. Its weight is redistributed proportionally across
    the categories that can actually be evaluated.
    """
    active_components = [
        component
        for component, score in component_scores.items()
        if score is not None
    ]

    if not active_components:
        return {}

    total_active_weight = sum(
        weights.get(component, 0.0)
        for component in active_components
    )

    if total_active_weight <= 0:
        return {}

    normalized_weights = {}

    for component in active_components:
        original_weight = weights.get(component, 0.0)

        normalized_weights[component] = (
            original_weight / total_active_weight
        ) * 100.0

    return normalized_weights


# ---------------------------------------------------------------------------
# Final ATS score
# ---------------------------------------------------------------------------

def calculate_ats_score(
    match_analysis: dict[str, Any],
    *,
    resume_analysis: dict[str, Any] | None = None,
    parseability_analysis: dict[str, Any] | None = None,
    weights: dict[str, float] | None = None,
) -> dict[str, Any]:
    """
    Calculate the final Novus ATS score.

    Args:
        match_analysis:
            Output from ATS-03 build_match_analysis().

        resume_analysis:
            Normalized resume analysis from ATS-01.

        parseability_analysis:
            Future structure/parseability analysis.

        weights:
            Optional custom scoring weights.

    Returns:
        Structured, explainable scoring result.
    """
    if not isinstance(match_analysis, dict):
        raise ValueError("Match analysis must be a dictionary.")

    scoring_weights = dict(
        DEFAULT_WEIGHTS
        if weights is None
        else weights
    )

    if not scoring_weights:
        raise ValueError("Scoring weights cannot be empty.")

    if any(
        not isinstance(value, (int, float)) or value < 0
        for value in scoring_weights.values()
    ):
        raise ValueError(
            "Scoring weights must contain non-negative numbers."
        )

    component_scores = calculate_component_scores(
        match_analysis,
        resume_analysis=resume_analysis,
        parseability_analysis=parseability_analysis,
    )

    active_weights = _active_weights(
        component_scores,
        scoring_weights,
    )

    if not active_weights:
        return {
            "score": 0.0,
            "component_scores": component_scores,
            "weights": {},
            "weighted_components": {},
        }

    weighted_components: dict[str, float] = {}

    for component, weight in active_weights.items():
        component_score = component_scores[component]

        if component_score is None:
            continue

        weighted_components[component] = (
            component_score * weight / 100.0
        )

    final_score = sum(weighted_components.values())

    return {
        "score": _round_score(final_score),

        "component_scores": {
            component: (
                None
                if score is None
                else _round_score(score)
            )
            for component, score in component_scores.items()
        },

        "weights": {
            component: _round_score(weight)
            for component, weight in active_weights.items()
        },

        "weighted_components": {
            component: _round_score(value)
            for component, value in weighted_components.items()
        },
    }


# ---------------------------------------------------------------------------
# Score interpretation
# ---------------------------------------------------------------------------

def get_score_level(score: float) -> str:
    """
    Convert a numeric ATS score into a human-readable level.
    """
    if score >= 85:
        return "Excellent"

    if score >= 70:
        return "Strong"

    if score >= 55:
        return "Moderate"

    if score >= 40:
        return "Needs Improvement"

    return "Weak"


def build_score_summary(
    score_result: dict[str, Any],
) -> dict[str, Any]:
    """
    Build a compact explanation of the final ATS score.
    """
    score = float(
        score_result.get("score", 0.0)
    )

    component_scores = score_result.get(
        "component_scores",
        {},
    )

    valid_components = [
        (name, value)
        for name, value in component_scores.items()
        if isinstance(value, (int, float))
    ]

    strongest_component = None
    weakest_component = None

    if valid_components:
        strongest_component = max(
            valid_components,
            key=lambda item: item[1],
        )[0]

        weakest_component = min(
            valid_components,
            key=lambda item: item[1],
        )[0]

    return {
        "score": score,
        "level": get_score_level(score),
        "strongest_component": strongest_component,
        "weakest_component": weakest_component,
    }